server:
  port: 8090
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:

  thymeleaf:
    cache: false
    mode: HTML5
    content-type: text/html
    encoding: UTF-8

  #datasource:
    #url : jdbc:mysql://127.0.0.1:3306/mobile_2016?useUnicode:true&characterEncoding:UTF-8
    #username : root
    #password : 123456
    #driverClassName : com.mysql.jdbc.Driver
    #maximumPoolSize : 25
    #minimumIdle : 3
    #idleTimeout : 30000
    #pool-prepared-statements : true
    #max-open-prepared-statements : 250


druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
          url: jdbc:mysql://10.200.157.33:3306/mobile_2016?characterEncoding:UTF-8&autoReconnect:true&zeroDateTimeBehavior:convertToNull&useUnicode:true
          driver-class-name: com.mysql.jdbc.Driver
          username: caoyamin
          password: 123456
          filters: stat,wall
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxOpenPreparedStatements: 20
          slowSqlMillis: 5000
          isLogSlowSql: true
    slave:
          url: jdbc:mysql://10.200.108.21:3306/mobile_2016?characterEncoding:UTF-8&autoReconnect:true&zeroDateTimeBehavior:convertToNull&useUnicode:true&characterEncoding:utf-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          filters: stat,wall
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxOpenPreparedStatements: 20
          slowSqlMillis: 5000
          isLogSlowSql: true




redis:
      # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
      database: 0
      # redis服务器地址（默认为localhost）
      host: 127.0.0.1
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password:
      # redis连接超时时间（单位为毫秒）
      timeout: 30
      # redis连接池配置
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
jwt:
   header: Authorization
   secret: mode2016
   expiration: 604800

# mybatis配置
mybatis:

  config-location: classpath:mybatis-config.xml
  # 配置映射类所在包名
  #type-aliases-package: com.mobile2016.backend.mapper
  # 配置mapper xml文件所在路径，这里是一个数组
  #mapper-locations:
    #- mappers/UserMapper.xml


logging:
  config: classpath:logback-warn.xml
  level:
    com.wooyoo.learning: DEBUG





